### ISSUE TITLE
Upgrade Microsoft.Data.SqlClient 3.0.0 to support Active Directory Default authentication

### ISSUE THREAD

**Issue by pherbel** [chriswill/DbUpReboot#4]
Hello,

We have just started to use your DbUp fork and it is great because of the Microsoft.Data.SqlClient support

Do you have plan to upgrade to 3.0.0?

https://docs.microsoft.com/en-us/sql/connect/ado-net/sql/azure-active-directory-authentication?view=sql-server-ver15

**Comment by chriswill** [comment]
Hi @pherbel!,

Version 1.1.0 has been published just now which includes all updated dependencies, including Microsoft.Data.SqlClient 3.0.0.

**Comment by pherbel** [comment]
wow! Thanks

I will test it.
