### ISSUE TITLE
Migration from Microsoft.Azure.Services.AppAuthentication to Azure.Identity

### ISSUE THREAD

**Issue by techarch** [chriswill/DbUpReboot#7]
First kudos for all the efforts to date to bring DbUp to a more modern stack. DbUp is a fantastic tool. :-)
Microsoft.Azure.Services.AppAuthentication is no longer recommended and Azure.Identity should be used instead per Microsoft - see https://docs.microsoft.com/en-us/dotnet/api/overview/azure/app-auth-migration. We are on an endless upgrade treadmill! ;-)

Migrating to the new library would also make it possible to enhance DbUpReboot to support user-assigned managed identities (passwordless service principals) in Azure. This provides significant security benefits as no sensitive credentials are ever used, andna managed identity can only be used from inside Azure itself. 
Currently the AzureSqlConnectionManager uses AzureServiceTokenProvider which does not have a way to pass in the ClientID of a managed identity.
It would be awesome if these enhancements could be made as this would make it possible to run DbUp migrations either from an Azure Container Instance or from a job in Azure Kubernetes Service.

**Comment by chriswill** [comment]
Hi @techarch, yes we should be updating to take advantage of this.  I did a quick check and it looks like there is only one affected line in the app, although I'm just guessing that it's an easy migration because I haven't used this new library at all in any other project. 

If you feel up for it, I think a PR would be great.  I just refreshed the project to take in another PR and to update all the libraries, so it's ready for tinkering if you care to.  Otherwise I should be able to take a look soon also.

**Comment by techarch** [comment]
Hi @chriswill, it took me a while to test the changes as they can only be used when running DbUpReboot from inside an Azure workload in the context of an user-assigned managed identity in Azure SQL, which is under-documented to say the least. Luckily the Microsoft FastTrack team was very helpful. They recommend that the App Id of the user-assigned managed identity be set in the User Id of the connection string. The SqlConnection then works with Azure Identity behind the scenes to get a token for that managed identity and set it on the connection.

**Comment by chriswill** [comment]
Thanks very much for the PR @techarch!  I appreciate the contribution.  I've merged and it's currently being built and distributed.

I recognize the documentation issues you encountered were the key blocker here. Glad you could get some assistance and figure it out and provide the path forward.
