### ISSUE TITLE
Vulnerability due to dependency on System.Drawing.Common@5.0.0

### ISSUE THREAD

**Issue by kurtwaldowski-echelon** [chriswill/DbUpReboot#9]
![image](https://user-images.githubusercontent.com/29380633/209757818-d4b856eb-e80f-4e7e-ba30-b95863c47e69.png)

https://security.snyk.io/vuln/SNYK-DOTNET-SYSTEMDRAWINGCOMMON-3063427

No immediate resolution available due to dependency on Microsoft.Data.SqlClient

**Comment by chriswill** [comment]
Hi, I released version 1.5.0 tonight which updates to Microsoft.Data.SqlClient 5.1.  Hopefully this resolves the issue.  Please close the issue if you think this is resolved.  I wasn't able to see one way or the other if this is still an issue in the latest SqlClient.

**Comment by kurtwaldowski-echelon** [comment]
@chriswill I followed the dependency links in the latest version (5.1), and this should resolve the issue. Thanks!
